require: rubocop-rails

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Force before_filter until upgrade to Rails 4
Rails/ActionFilter:
  EnforcedStyle: filter

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 9

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 9

Style/Next:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Gemspec/RequiredRubyVersion:
  Enabled: false
