inherit_from: .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - default.yml

Layout/LineLength:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/foreman_gaffer_tape/engine.rb'
    - 'test/**/*'
    - 'lib/foreman_netbox/engine.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/foreman_gaffer_tape/engine.rb'
    - 'test/**/*'

Rails/DynamicFindBy:
  Exclude:
    - 'app/interactors/**/*'
