name: CI
on: push
env:
  RAILS_ENV: test
  DATABASE_URL: postgresql://postgres:@localhost/test
  DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.3
      - name: Setup
        run: |
          gem install bundler
          bundle install --jobs=3 --retry=3
      - name: Run rubocop
        run: bundle exec rubocop
  test:
    runs-on: ubuntu-latest
    needs: rubocop
    services:
      postgres:
        image: postgres:12.1
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        foreman-core-branch: [1.24-stable, 2.0-stable, develop]
        ruby-version: [2.3, 2.5, 2.6]
        node-version: [10]
        exclude:
          - foreman-core-branch: 2.0-stable
            ruby-version: 2.3
          - foreman-core-branch: develop
            ruby-version: 2.3
    steps:
      - run: sudo apt-get install build-essential libcurl4-openssl-dev libvirt-dev ruby-libvirt zlib1g-dev libpq-dev
      - uses: actions/checkout@v2
        with:
          repository: netbox-community/netbox-docker
          ref: release
          path: netbox-docker
      - name: Setup Netbox
        working-directory: netbox-docker
        run: |
          tee docker-compose.override.yml <<EOF
          version: '3.4'
          services:
            nginx:
              ports:
              - 8000:8080
          EOF
          docker-compose pull
          docker-compose up -d
          sleep 90
      - uses: actions/checkout@v2
        with:
          repository: theforeman/foreman
          ref: ${{ matrix.foreman-core-branch }}
      - uses: actions/checkout@v2
        with:
          path: foreman_netbox
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version:  ${{ matrix.node-version }}
      - name: Setup Plugin
        run: |
          echo "gem 'foreman_netbox', path: './foreman_netbox'" > bundler.d/foreman_netbox.local.rb
          gem install bundler
          bundle config set without journald development console mysql2 sqlite
          bundle install --jobs=3 --retry=3
          bundle exec rake db:create
          bundle exec rake db:migrate
          npm install
          bundle exec rake webpack:compile
      - name: Run plugin tests
        run: |
          bundle exec rake test:foreman_netbox
          bundle exec rake test TEST="test/unit/foreman/access_permissions_test.rb"
        env:
          FOREMAN_NETBOX_URL: http://0.0.0.0:8000
          FOREMAN_NETBOX_TOKEN: 0123456789abcdef0123456789abcdef01234567
      - name: Precompile plugin assets
        run: bundle exec rake 'plugin:assets:precompile[foreman_netbox]'
        env:
          RAILS_ENV: production
