name: Ruby test

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rubocop:
    uses: theforeman/actions/.github/workflows/rubocop.yml@v0
    with:
      command: bundle exec rubocop --parallel --format github

  test:
    name: Ruby
    needs: rubocop
    strategy:
      fail-fast: false
      matrix:
        foreman:
          - "develop"
          - "3.14-stable"
          - "3.13-stable"
    uses: ./.github/workflows/foreman_plugin_netbox.yml
    with:
      plugin: foreman_netbox
      foreman_version: ${{ matrix.foreman }}
      netbox_version: 'v4.3'
      netbox_docker_version: '3.3.0'
      environment_variables: |
        FOREMAN_VERSION=${{ matrix.foreman }}
